### ISSUE TITLE
Add MAD-X format converter

### ISSUE THREAD

**Issue by felix-andreas** [andreasfelix/latticejson#10]

**Comment by tomerten** [comment]
I have a rough one, I will try to get something done in the next days.

**Comment by felix-andreas** [comment]
@tomerten could you send a PR with the converter? If you have not much time could you just post the code here?

I need a converter within the next days and would otherwise write my own implementation.

**Comment by tomerten** [comment]
Hi Felix,

Have a look in my bessy gitlab projects , it should be in the elegant simulation tools.
https://gitlab.acc.bessy.de/Mertens/ElegantSimTools/blob/master/ElegantSimTools/Utils/LatticeConversionUtils.py

Tom
