### ISSUE TITLE
Include energy to lattice file

### ISSUE THREAD

**Issue by PaulGoslawski** [andreasfelix/latticejson#14]
Currently the energy is not defined for the lattice!
It is needed for radiation integrals ...

Energy should be included as global parameter, because it is not element specific... nearly all elements depend on energy

@TMsangohan @andreasfelix

**Comment by tomerten** [comment]
@PaulGoslawski @andreasfelix 
Felix, I would not put the ps_value in the element definition (e.g. dipole) but in a separate settings dict, as it is not the values that are important but the power supply names and values (easier to compare models/lattice settings/ real machine) together with conversion factors. I also think Paul's suggestion of energy should then belong in this part.
