### ISSUE TITLE
[Discussion] Best way to organize elements/lattices

### ISSUE THREAD

**Issue by felix-andreas** [andreasfelix/latticejson#21]
**Option A - `{<name>: {"type": <type>, <attributes>}}`** (current structure) 

```json
"elements": {
    "D1": {"type": "Drift", "length": 0.55},
    "Q1": {"type": "Quadrupole", "length": 0.2, "k1": 1.2},
    "Q2": {"type": "Quadrupole", "length": 0.4, "k1": -1.2},
    "B1": {"type": "Dipole", "length": 1.5, "angle": 0.392701, "e1": 0.1963505, "e2": 0.1963505}
}
```
How to loop over all elements:
```python
for name, definition in elements.items():
    type_ = attributes["type"].pop()   
    attributes = definition
```

How to access single element by name:
```python
attributes = elements["NAME"].copy() # copy to avoid changing original dict
type_ = attributes.pop("type")
```

**Option B - `{<name>: [<type>, <attributes>]}`** 

```json
"elements": {
    "D1": ["Drift", {"length": 0.55}],
    "Q1": ["Quadrupole", {"length": 0.2, "k1": 1.2}],
    "Q2": ["Quadrupole", {"length": 0.4, "k1": -1.2}],
    "B1": ["Dipole", {"length": 1.5, "angle": 0.392701, "e1": 0.1963505, "e2": 0.1963505}]
}
```

How to loop over all elements:
```python
for name, (type_, attributes) in elements.items():
```

How to access single element by name:
```python
type_, attributes = elements["NAME"]
```

**Option C - `[[<name>, <type>, <attributes>]]`** 

```json
"elements": [
    ["D1", "Drift", {"length": 0.55}],
    ["Q1", "Quadrupole", {"length": 0.2, "k1": 1.2}],
    ["Q2", "Quadrupole", {"length": 0.4, "k1": -1.2}],
    ["B1", "Dipole", {"length": 1.5, "angle": 0.392701, "e1": 0.1963505, "e2": 0.1963505}]
]
```

How to loop over all elements: *(most concise)*
```python
for name, type_, attributes in elements:
```

How to access single element by name: (*Slower because one has to traverse list*)
```python
name, type_, attributes = next(x for x in elements if x[0] == "NAME") 
```

**Comment by felix-andreas** [comment]
@tomerten I am thinking about changing the latticeJSON structure to option **B**. 

When accessing the attributes of an element it is necessary to know its `type` before. With the current option **A** one has to split up the attributes dict into `type_` and the other `attributes`. I find myself repeatedly writing something like this:

```python
attributes = elements[name].copy() # copy to avoid changing the original dict
type_ = attributes.pop("type")
```

With option **B** this would simplify to:

```python
type_, attributes = elements[name]
```

I think this is also a bit more intuitive because the `type` defines which `attributes` an element has.  Therefore one could argue they are logical not on the same level and hence should not belong within the same dict... 

But I am not sure if this is worth the extra level of nesting...

**Comment by PaulGoslawski** [comment]
Go for option B !
