### ISSUE TITLE
Nested JSON tree print

### ISSUE THREAD

**Issue by TMsangohan** [andreasfelix/latticejson#3]
The print tree method you used in apace does not work completely properly if the nesting level is larger than 3. I have a solution, which is the implementation of the linux tree command in python but applied to dictionaries. 

Should we add it?

**Comment by felix-andreas** [comment]
Sound great. Please do a PR. 

We could definitively add this functionality to the CLI.

Something like
```bash
latticejson show tree /path/to/lattice
```

But we have to discuss the scope of this repo (see #4). I would like to keep this repo independent of Python. So that this repo would only contain the CLI and the schema files. What is your opinion?

**Comment by TMsangohan** [comment]
In principle I agree with you that we should try to keep the repo independent of Python. But in that case how would you do the (elegant, ...) converters? You would, create a new repo (latticejsonPythonTools)?

**Comment by felix-andreas** [comment]
What I meant with independent, this repo should only contain the definition and a tool to validate/convert lattice files. In which language this cli tool is implemented should be no concern to the user.

Then there should be a other repo which contains an Python API to load/save/manipulate lattice files. This should pylatticetools or apace (we have to discuss this) ...

**Comment by TMsangohan** [comment]
Ah ok I see. 

Yes, let us discuss the pylatticetools soon. I am working on a similar tool (financejson), and I have similar concerns :). I'll send you a link to the tool soon (working on unit tests) and converters (Excel, HDF5, SQL, MongoDB, etc...).

**Comment by felix-andreas** [comment]
fixed by #50
