### ISSUE TITLE
Add cavity to specification

### ISSUE THREAD

**Issue by felix-andreas** [andreasfelix/latticejson#9]
I think we should add a cavity element to the specification!

@TMsangohan, do you have some suggestions. If you could write down a short summary off the cavity element similar to #2, I would add it to the `schema.json`.

**Comment by tomerten** [comment]
```
Cavity
   Voltage
   Frequency
   Phase
   Fiducial (optional)
   End1_Focus (optional)
   End2_Focus (optional)
   Body_Focus_Model (optional)
  
```

**Comment by felix-andreas** [comment]
Should the phase attribute be required (not optional)?

**Comment by PaulGoslawski** [comment]
A Phase attribute is absolutly mandatory! in order to track with and without synchrotron radiation or in more general to accelerate or deaccelerate the beam.

**Comment by TMsangohan** [comment]
Hi Felix,

What is the status on this? I also need cavities to convert my latest lattice, even just having
```
- Length
- Voltage
- Frequency
- Phase
```

would be good.

Tom
